# Generated by Django 5.2.6 on 2025-09-19 02:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the expertise category', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the expertise category', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the category was created')),
            ],
            options={
                'verbose_name': 'Expertise Category',
                'verbose_name_plural': 'Expertise Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NarasumberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the narasumber', max_length=200)),
                ('bio', models.TextField(help_text='Biography or description of the narasumber')),
                ('experience_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], help_text='Level of experience in the expertise area', max_length=15)),
                ('years_of_experience', models.PositiveIntegerField(help_text='Number of years of experience', validators=[django.core.validators.MinValueValidator(0)])),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20, null=True)),
                ('is_phone_public', models.BooleanField(default=False, help_text='Whether to display phone number publicly')),
                ('location', models.CharField(choices=[('aceh', 'Aceh'), ('sumatera_utara', 'Sumatera Utara'), ('sumatera_selatan', 'Sumatera Selatan'), ('sumatera_barat', 'Sumatera Barat'), ('bengkulu', 'Bengkulu'), ('riau', 'Riau'), ('kepulauan_riau', 'Kepulauan Riau'), ('jambi', 'Jambi'), ('lampung', 'Lampung'), ('bangka_belitung', 'Bangka Belitung'), ('kalimantan_barat', 'Kalimantan Barat'), ('kalimantan_timur', 'Kalimantan Timur'), ('kalimantan_selatan', 'Kalimantan Selatan'), ('kalimantan_tengah', 'Kalimantan Tengah'), ('kalimantan_utara', 'Kalimantan Utara'), ('banten', 'Banten'), ('dki_jakarta', 'DKI Jakarta'), ('jawa_barat', 'Jawa Barat'), ('jawa_tengah', 'Jawa Tengah'), ('daerah_istimewa_yogyakarta', 'Daerah Istimewa Yogyakarta'), ('jawa_timur', 'Jawa Timur'), ('bali', 'Bali'), ('nusa_tenggara_timur', 'Nusa Tenggara Timur'), ('nusa_tenggara_barat', 'Nusa Tenggara Barat'), ('gorontalo', 'Gorontalo'), ('sulawesi_barat', 'Sulawesi Barat'), ('sulawesi_tengah', 'Sulawesi Tengah'), ('sulawesi_utara', 'Sulawesi Utara'), ('sulawesi_tenggara', 'Sulawesi Tenggara'), ('sulawesi_selatan', 'Sulawesi Selatan'), ('maluku_utara', 'Maluku Utara'), ('maluku', 'Maluku'), ('papua_barat', 'Papua Barat'), ('papua_barat_daya', 'Papua Barat Daya'), ('papua_tengah', 'Papua Tengah'), ('papua', 'Papua'), ('papua_selatan', 'Papua Selatan'), ('papua_pegunungan', 'Papua Pegunungan')], help_text='Province/location in Indonesia', max_length=50)),
                ('portfolio_link', models.URLField(blank=True, help_text='Portfolio website URL (optional)', null=True, validators=[django.core.validators.URLValidator()])),
                ('social_media_links', models.JSONField(blank=True, default=dict, help_text="Social media links in JSON format (e.g., {'linkedin': 'url', 'twitter': 'url'})")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the profile was last updated')),
                ('expertise_area', models.ForeignKey(help_text='Area of expertise', on_delete=django.db.models.deletion.CASCADE, related_name='narasumber_profiles', to='narasumber.expertisecategory')),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='narasumber_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Narasumber Profile',
                'verbose_name_plural': 'Narasumber Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
