# Generated by Django 4.2.23 on 2025-09-29 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('narasumber', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='narasumberprofile',
            name='user',
            field=models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='narasumber_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='education',
            name='narasumber_profile',
            field=models.ForeignKey(help_text='Associated narasumber profile', on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='narasumber.narasumberprofile'),
        ),
    ]
