# Generated by Django 4.2.23 on 2025-09-21 13:40

from django.db import migrations, models
import narasumber.models


class Migration(migrations.Migration):

    dependencies = [
        ('narasumber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='narasumberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture for the narasumber (optional)', null=True, upload_to=narasumber.models.narasumber_profile_picture_upload_path),
        ),
    ]
