# Generated by Django 5.2.6 on 2025-09-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narasumber', '0002_narasumberprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narasumberprofile',
            name='social_media_links',
            field=models.JSONField(blank=True, default=list, help_text="Social media links in JSON format (e.g., [{'title': 'LinkedIn', 'url': 'https://linkedin.com/in/user'}])"),
        ),
    ]
