# Generated by Django 4.2.23 on 2025-09-30 01:12

from django.db import migrations, models
import django.db.models.deletion
import narasumber.models
import narrapro.simple_storage


class Migration(migrations.Migration):

    dependencies = [
        ('narasumber', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narasumberprofile',
            name='expertise_area',
            field=models.ForeignKey(help_text='Area of expertise', on_delete=django.db.models.deletion.PROTECT, related_name='narasumber_profiles', to='narasumber.expertisecategory'),
        ),
        migrations.AlterField(
            model_name='narasumberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture for the narasumber (optional)', null=True, storage=narrapro.simple_storage.SimpleSupabaseStorage(), upload_to=narasumber.models.narasumber_profile_picture_upload_path),
        ),
    ]
