# Generated by Django 5.2.6 on 2025-09-30 04:45

import narasumber.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narasumber', '0003_alter_narasumberprofile_expertise_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narasumberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture for the narasumber (optional)', null=True, upload_to=narasumber.models.narasumber_profile_picture_upload_path),
        ),
    ]
