# Generated by Django 5.2.6 on 2025-09-22 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narasumber', '0003_alter_narasumberprofile_social_media_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narasumberprofile',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='narasumberprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL (optional)', null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
