# Generated by Django 4.2.23 on 2025-09-28 05:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narasumber', '0004_replace_social_media_with_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('SMA', 'SMA/SMK/Sederajat'), ('D3', 'Diploma 3 (D3)'), ('S1', 'Sarjana (S1)'), ('S2', 'Magister (S2)'), ('S3', 'Doktor (S3)'), ('Certificate', 'Sertifikat Profesional'), ('Other', 'Lainnya')], help_text='Type of degree or education level', max_length=20)),
                ('school_university', models.CharField(help_text='Name of school, university, or institution', max_length=200)),
                ('field_of_study', models.CharField(blank=True, help_text='Field of study or major (optional)', max_length=200, null=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, help_text='Year of graduation (optional)', null=True, validators=[django.core.validators.MinValueValidator(1950)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this education entry was created')),
                ('narasumber_profile', models.ForeignKey(help_text='Associated narasumber profile', on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='narasumber.narasumberprofile')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-graduation_year', '-created_at'],
            },
        ),
    ]
