# Generated by Django 4.2.23 on 2025-09-28 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narasumber', '0005_add_education_model'),
    ]

    operations = [
    ]
