# Generated by Django 4.2.23 on 2025-10-07 04:09

from django.db import migrations, models
import django.db.models.deletion
import narasumber.models


class Migration(migrations.Migration):

    dependencies = [
        ('narasumber', '0007_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narasumberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture for the narasumber (optional)', null=True, upload_to=narasumber.models.narasumber_profile_picture_upload_path),
        ),
        migrations.CreateModel(
            name='ProfessionalCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or name of the certification', max_length=200)),
                ('description', models.TextField(help_text='Description of the certification, issuing organization, or other details')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this certification entry was created')),
                ('narasumber_profile', models.ForeignKey(help_text='Associated narasumber profile', on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='narasumber.narasumberprofile')),
            ],
            options={
                'verbose_name': 'Professional Certification',
                'verbose_name_plural': 'Professional Certifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
