# Generated by Django 4.2.23 on 2025-10-10 03:55

from django.db import migrations, models
import narasumber.models
import narrapro.simple_storage


class Migration(migrations.Migration):

    dependencies = [
        ('narasumber', '0008_alter_narasumberprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narasumberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture for the narasumber (optional)', null=True, storage=narrapro.simple_storage.SimpleSupabaseStorage(), upload_to=narasumber.models.narasumber_profile_picture_upload_path),
        ),
    ]
