# Generated by Django 5.2.6 on 2025-10-01 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The event organizer making the booking', limit_choices_to={'user_type': 'event'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('', 'Pilih Role'), ('narasumber', 'Narasumber'), ('event', 'Event'), ('pengguna', 'Pengguna')], help_text='Type of user account', max_length=20),
        ),
    ]
