# Generated by Django 4.2.23 on 2025-09-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('', 'Pilih Role'), ('narasumber', 'Narasumber'), ('event', 'Event')], help_text='Type of user account', max_length=20),
        ),
    ]
