# Generated by Django 5.2.6 on 2025-10-08 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_booking_event_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation request from event/pengguna', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when cancellation was requested', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_requested_by',
            field=models.ForeignKey(blank=True, help_text='User who requested the cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('CANCELED', 'Dibatalkan'), ('CANCELLATION_REQUESTED', 'Permintaan Pembatalan')], default='PENDING', help_text='The current status of the booking', max_length=25),
        ),
    ]
