# Generated by Django 5.1 on 2025-09-22 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], default='PENDING', help_text='The current status of the booking', max_length=10)),
                ('booking_date', models.DateTimeField(help_text='The date and time of the booking')),
                ('message', models.TextField(blank=True, help_text='A message from the event organizer to the narasumber')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='The event organizer making the booking', limit_choices_to={'user_type': 'event'}, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_bookings', to=settings.AUTH_USER_MODEL)),
                ('narasumber', models.ForeignKey(help_text='The narasumber being booked', limit_choices_to={'user_type': 'narasumber'}, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_date'],
            },
        ),
    ]
