# Generated by Django 5.2.6 on 2025-09-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('CANCELED', 'Dibatalkan')], default='PENDING', help_text='The current status of the booking', max_length=10),
        ),
    ]
