# Generated by Django 4.2.23 on 2025-09-29 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('narasumber', '0001_initial'),
        ('lowongan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lowonganapplication',
            name='applicant',
            field=models.ForeignKey(help_text='The narasumber user applying', on_delete=django.db.models.deletion.CASCADE, related_name='lowongan_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lowonganapplication',
            name='lowongan',
            field=models.ForeignKey(help_text='The lowongan being applied for', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='lowongan.lowongan'),
        ),
        migrations.AddField(
            model_name='lowongan',
            name='created_by',
            field=models.ForeignKey(help_text='Event user who created this lowongan', on_delete=django.db.models.deletion.CASCADE, related_name='lowongan_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lowongan',
            name='expertise_category',
            field=models.ForeignKey(help_text='Required expertise category', on_delete=django.db.models.deletion.CASCADE, related_name='lowongan_opportunities', to='narasumber.expertisecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='lowonganapplication',
            unique_together={('lowongan', 'applicant')},
        ),
    ]
