"""
Django settings for narrapro project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", 'django-insecure-t!da#x47!qeo%09c%&cse1q(6#g)@ns40127@%xx6r7#15rl&$')

# SECURITY WARNING: don't run with debug turned on in production!
if os.getenv("PRODUCTION") == "true":
    DEBUG = False
else:
    DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'anymail',
    'profiles',
    'main',
    'narasumber',
    'lowongan',
    'event',
    'search',
    'pengguna',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'narrapro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'narrapro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


if os.getenv("PRODUCTION") == "true":
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(
            os.getenv("DATABASE_URL"))
    }
    DATABASES['default']['CONN_MAX_AGE'] = 600
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Static files configuration
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Set STATIC_ROOT for both development and production
STATIC_ROOT = BASE_DIR / "staticfiles"

# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG:
    # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
    # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
    # and renames the files with unique names for each version to support long-term caching
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Storage Configuration
print(f"SETTINGS DEBUG: PRODUCTION env var = '{os.getenv('PRODUCTION')}'")
print(f"SETTINGS DEBUG: Checking storage configuration...")

if os.getenv("PRODUCTION") == "true":
    print(f"SETTINGS DEBUG: Production mode detected, setting up Supabase storage")
    # Supabase Storage Configuration for Production
    DEFAULT_FILE_STORAGE = 'narrapro.simple_storage.SimpleSupabaseStorage'

    # Test import to make sure it works
    try:
        from narrapro.simple_storage import SimpleSupabaseStorage
        print(f"SETTINGS DEBUG: SimpleSupabaseStorage import successful")
    except Exception as e:
        print(f"SETTINGS DEBUG: ERROR importing SimpleSupabaseStorage: {e}")

    # Media URL will be constructed by custom storage backend
    MEDIA_URL = f"{os.getenv('SUPABASE_URL')}/storage/v1/object/public/{os.getenv('SUPABASE_BUCKET_NAME', 'storage')}/"
    print(f"SETTINGS DEBUG: DEFAULT_FILE_STORAGE set to: {DEFAULT_FILE_STORAGE}")
    print(f"SETTINGS DEBUG: MEDIA_URL set to: {MEDIA_URL}")
else:
    print(f"SETTINGS DEBUG: Development mode, using local storage")
    # Local development settings
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'profiles.User'

# Email Configuration (Resend SMTP via django-anymail)
EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'
ANYMAIL = {
    'RESEND_API_KEY': os.getenv('RESEND_API_KEY'),
}
DEFAULT_FROM_EMAIL = 'onboarding@resend.dev'


# Tailwind CSS Configuration
TAILWIND_APP_NAME = 'theme'
if DEBUG:
    INSTALLED_APPS += ['django_browser_reload']
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

# NPM CONFIGURATION
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd" # Adjust this path if necessary

# CSRF_TRUSTED_ORIGINS
CSRF_TRUSTED_ORIGINS = [
    'https://narrapro.up.railway.app',
    # Add your actual production domain here
]