# Generated by Django 5.2.6 on 2025-09-19 02:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event or organization', max_length=200)),
                ('description', models.TextField(help_text='Description of the event or organization')),
                ('location', models.CharField(choices=[('aceh', 'Aceh'), ('sumatera_utara', 'Sumatera Utara'), ('sumatera_selatan', 'Sumatera Selatan'), ('sumatera_barat', 'Sumatera Barat'), ('bengkulu', 'Bengkulu'), ('riau', 'Riau'), ('kepulauan_riau', 'Kepulauan Riau'), ('jambi', 'Jambi'), ('lampung', 'Lampung'), ('bangka_belitung', 'Bangka Belitung'), ('kalimantan_barat', 'Kalimantan Barat'), ('kalimantan_timur', 'Kalimantan Timur'), ('kalimantan_selatan', 'Kalimantan Selatan'), ('kalimantan_tengah', 'Kalimantan Tengah'), ('kalimantan_utara', 'Kalimantan Utara'), ('banten', 'Banten'), ('dki_jakarta', 'DKI Jakarta'), ('jawa_barat', 'Jawa Barat'), ('jawa_tengah', 'Jawa Tengah'), ('daerah_istimewa_yogyakarta', 'Daerah Istimewa Yogyakarta'), ('jawa_timur', 'Jawa Timur'), ('bali', 'Bali'), ('nusa_tenggara_timur', 'Nusa Tenggara Timur'), ('nusa_tenggara_barat', 'Nusa Tenggara Barat'), ('gorontalo', 'Gorontalo'), ('sulawesi_barat', 'Sulawesi Barat'), ('sulawesi_tengah', 'Sulawesi Tengah'), ('sulawesi_utara', 'Sulawesi Utara'), ('sulawesi_tenggara', 'Sulawesi Tenggara'), ('sulawesi_selatan', 'Sulawesi Selatan'), ('maluku_utara', 'Maluku Utara'), ('maluku', 'Maluku'), ('papua_barat', 'Papua Barat'), ('papua_barat_daya', 'Papua Barat Daya'), ('papua_tengah', 'Papua Tengah'), ('papua', 'Papua'), ('papua_selatan', 'Papua Selatan'), ('papua_pegunungan', 'Papua Pegunungan')], help_text='Province/location in Indonesia where events are held', max_length=50)),
                ('contact', models.CharField(help_text='Contact information (phone, email, or other contact method)', max_length=200)),
                ('website', models.URLField(blank=True, help_text='Event or organization website URL (optional)', null=True, validators=[django.core.validators.URLValidator()])),
                ('cover_image', models.ImageField(help_text='Cover image for the event or organization', upload_to='event_covers/')),
                ('start_date', models.DateField(blank=True, help_text='Start date for one-time events (optional)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date for one-time events (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the profile was last updated')),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='event_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Profile',
                'verbose_name_plural': 'Event Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
