# Generated by Django 5.2.6 on 2025-09-19 03:24

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprofile',
            name='cover_image',
            field=models.ImageField(help_text='Cover image for the event or organization', upload_to=event.models.event_cover_upload_path),
        ),
    ]
