# Generated by Django 4.2.23 on 2025-09-29 16:08

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprofile',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the event or organization (recommended)', null=True, upload_to=event.models.event_cover_upload_path),
        ),
    ]
