# Generated by Django 4.2.23 on 2025-09-21 13:40

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_update_cover_image_upload_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture for the event organizer (optional)', null=True, upload_to=event.models.event_profile_picture_upload_path),
        ),
    ]
