# Generated by Django 4.2.23 on 2025-09-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventprofile',
            name='contact',
        ),
        migrations.AddField(
            model_name='eventprofile',
            name='email',
            field=models.EmailField(default='perak@fasilkom.com', help_text='Contact email address', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventprofile',
            name='is_phone_public',
            field=models.BooleanField(default=False, help_text='Whether to display phone number publicly'),
        ),
        migrations.AddField(
            model_name='eventprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number (optional)', max_length=20, null=True),
        ),
    ]
