# Generated by Django 5.2.6 on 2025-09-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_eventprofile_contact_eventprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprofile',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict, help_text="Social media links in JSON format (e.g., {'linkedin': 'url', 'twitter': 'url'})"),
        ),
    ]
