# Generated by Django 5.2.6 on 2025-10-01 04:45

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_eventprofile_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprofile',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the event or organization (recommended)', null=True, upload_to=event.models.event_cover_upload_path),
        ),
    ]
