# Generated by Django 5.2.6 on 2025-09-22 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventprofile_social_media_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventprofile',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='eventprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL (optional)', null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
