# Generated by Django 4.2.23 on 2025-10-07 05:00

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_eventprofile_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprofile',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the event or organization (recommended)', null=True, upload_to=event.models.event_cover_upload_path),
        ),
    ]
