# Generated by Django 4.2.23 on 2025-09-27 01:54

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_replace_social_media_with_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprofile',
            name='cover_image',
            field=models.ImageField(help_text='Cover image for the event or organization (required)', upload_to=event.models.event_cover_upload_path),
        ),
    ]
