# Generated by Django 4.2.23 on 2025-09-27 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventprofile',
            name='profile_picture',
        ),
    ]
