# Generated by Django 4.2.23 on 2025-09-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_profile_picture_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprofile',
            name='event_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='offline', help_text='Type of event: Online, Offline, or Hybrid', max_length=10),
        ),
        migrations.AddField(
            model_name='eventprofile',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Description of the target audience for this event (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='eventprofile',
            name='location',
            field=models.CharField(help_text='Location/platform where events are held', max_length=50),
        ),
    ]
