# Generated by Django 5.2.6 on 2025-10-01 04:45

import django.core.validators
import django.db.models.deletion
import pengguna.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenggunaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_topic', models.CharField(help_text='Topik wawancara atau tujuan booking', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Deskripsi singkat tentang wawancara', null=True)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('offline', 'Offline (tatap muka)')], default='zoom', help_text='Media untuk wawancara', max_length=100)),
                ('location_detail', models.CharField(blank=True, help_text='Detail lokasi jika wawancara offline', max_length=255, null=True)),
                ('contact_email', models.EmailField(help_text='Email kontak pengguna', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Nomor telepon pengguna (opsional)', max_length=20, null=True)),
                ('is_phone_public', models.BooleanField(default=False, help_text='Apakah nomor telepon ditampilkan ke narasumber')),
                ('website', models.URLField(blank=True, help_text='Website terkait wawancara (opsional)', null=True, validators=[django.core.validators.URLValidator()])),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn (opsional)', null=True, validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='Relasi ke booking asli', on_delete=django.db.models.deletion.CASCADE, related_name='pengguna_extension', to='profiles.booking')),
                ('pengguna', models.ForeignKey(help_text='Pengguna biasa yang membuat booking', limit_choices_to={'user_type': 'pengguna'}, on_delete=django.db.models.deletion.CASCADE, related_name='pengguna_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengguna Booking',
                'verbose_name_plural': 'Pengguna Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PenggunaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Nama lengkap pengguna', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Tentang pengguna (opsional)', null=True)),
                ('email', models.EmailField(help_text='Alamat email pengguna', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Nomor telepon (opsional)', max_length=20, null=True)),
                ('is_phone_public', models.BooleanField(default=False, help_text='Apakah nomor telepon ditampilkan secara publik')),
                ('avatar', models.ImageField(blank=True, help_text='Foto profil pengguna', null=True, upload_to=pengguna.models.pengguna_avatar_upload_path)),
                ('website', models.URLField(blank=True, help_text='Website pribadi (opsional)', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn (opsional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User account yang terkait', on_delete=django.db.models.deletion.CASCADE, related_name='pengguna_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengguna Profile',
                'verbose_name_plural': 'Pengguna Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
