# Generated by Django 5.2.6 on 2025-10-05 07:06

import pengguna.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penggunaprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Foto profil pengguna (opsional)', null=True, upload_to=pengguna.models.pengguna_profile_picture_upload_path),
        ),
    ]
