# Generated by Django 4.2.23 on 2025-10-10 03:55

from django.db import migrations, models
import narrapro.simple_storage
import pengguna.models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0004_alter_penggunaprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penggunaprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Foto profil pengguna (opsional)', null=True, storage=narrapro.simple_storage.SimpleSupabaseStorage(), upload_to=pengguna.models.pengguna_profile_picture_upload_path),
        ),
    ]
